### ISSUE TITLE
node-cache must be dependency, not devDependency

### ISSUE THREAD

**Issue by nuest** [battlejj/express-mongoose-store#6]
Use of `node-cache` has been introduced in https://github.com/battlejj/express-mongoose-store/pull/4 but the dependency is only declared as a development dependency, resulting in a missing module exception when using version `1.0.6` from npm.

@battlejj need a PR or can you quickly fix this?

**Comment by battlejj** [comment]
@nuest yeah, gimme a min

**Comment by battlejj** [comment]
@nuest should be good to go, let me know if you have any issue.
